package com.zhaohai.rocketmq.network.protocol.mysql.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zhaohai.rocketmq.network.protocol.mysql.entity.MessageData;

public interface MessageDataMapper extends BaseMapper<MessageData> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    int insert(MessageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    int insertSelective(MessageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    MessageData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageData record);
}