package com.zhaohai.rocketmq.network.protocol.hbase.entity;

import java.io.Serializable;
import java.util.Date;

public class MessageData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.consume_site_date
     *
     * @mbggenerated
     */
    private Date consumeSiteDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.name_srv_addr
     *
     * @mbggenerated
     */
    private String nameSrvAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.instance_id
     *
     * @mbggenerated
     */
    private String instanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.messag_id
     *
     * @mbggenerated
     */
    private String messagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_data.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_data
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.id
     *
     * @return the value of message_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.id
     *
     * @param id the value for message_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.create_date
     *
     * @return the value of message_data.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.create_date
     *
     * @param createDate the value for message_data.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.update_date
     *
     * @return the value of message_data.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.update_date
     *
     * @param updateDate the value for message_data.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.consume_site_date
     *
     * @return the value of message_data.consume_site_date
     *
     * @mbggenerated
     */
    public Date getConsumeSiteDate() {
        return consumeSiteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.consume_site_date
     *
     * @param consumeSiteDate the value for message_data.consume_site_date
     *
     * @mbggenerated
     */
    public void setConsumeSiteDate(Date consumeSiteDate) {
        this.consumeSiteDate = consumeSiteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.is_deleted
     *
     * @return the value of message_data.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.is_deleted
     *
     * @param isDeleted the value for message_data.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.name_srv_addr
     *
     * @return the value of message_data.name_srv_addr
     *
     * @mbggenerated
     */
    public String getNameSrvAddr() {
        return nameSrvAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.name_srv_addr
     *
     * @param nameSrvAddr the value for message_data.name_srv_addr
     *
     * @mbggenerated
     */
    public void setNameSrvAddr(String nameSrvAddr) {
        this.nameSrvAddr = nameSrvAddr == null ? null : nameSrvAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.instance_id
     *
     * @return the value of message_data.instance_id
     *
     * @mbggenerated
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.instance_id
     *
     * @param instanceId the value for message_data.instance_id
     *
     * @mbggenerated
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId == null ? null : instanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.topic
     *
     * @return the value of message_data.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.topic
     *
     * @param topic the value for message_data.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.group_id
     *
     * @return the value of message_data.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.group_id
     *
     * @param groupId the value for message_data.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.messag_id
     *
     * @return the value of message_data.messag_id
     *
     * @mbggenerated
     */
    public String getMessagId() {
        return messagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.messag_id
     *
     * @param messagId the value for message_data.messag_id
     *
     * @mbggenerated
     */
    public void setMessagId(String messagId) {
        this.messagId = messagId == null ? null : messagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.tag
     *
     * @return the value of message_data.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.tag
     *
     * @param tag the value for message_data.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.key
     *
     * @return the value of message_data.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.key
     *
     * @param key the value for message_data.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_data.message
     *
     * @return the value of message_data.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_data.message
     *
     * @param message the value for message_data.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MessageData other = (MessageData) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getConsumeSiteDate() == null ? other.getConsumeSiteDate() == null : this.getConsumeSiteDate().equals(other.getConsumeSiteDate()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getNameSrvAddr() == null ? other.getNameSrvAddr() == null : this.getNameSrvAddr().equals(other.getNameSrvAddr()))
            && (this.getInstanceId() == null ? other.getInstanceId() == null : this.getInstanceId().equals(other.getInstanceId()))
            && (this.getTopic() == null ? other.getTopic() == null : this.getTopic().equals(other.getTopic()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getMessagId() == null ? other.getMessagId() == null : this.getMessagId().equals(other.getMessagId()))
            && (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getConsumeSiteDate() == null) ? 0 : getConsumeSiteDate().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getNameSrvAddr() == null) ? 0 : getNameSrvAddr().hashCode());
        result = prime * result + ((getInstanceId() == null) ? 0 : getInstanceId().hashCode());
        result = prime * result + ((getTopic() == null) ? 0 : getTopic().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getMessagId() == null) ? 0 : getMessagId().hashCode());
        result = prime * result + ((getTag() == null) ? 0 : getTag().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_data
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", consumeSiteDate=").append(consumeSiteDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", nameSrvAddr=").append(nameSrvAddr);
        sb.append(", instanceId=").append(instanceId);
        sb.append(", topic=").append(topic);
        sb.append(", groupId=").append(groupId);
        sb.append(", messagId=").append(messagId);
        sb.append(", tag=").append(tag);
        sb.append(", key=").append(key);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}